export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './detector.service';
import { DetectorService } from './detector.service';
export * from './detector.serviceInterface';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './project.serviceInterface';
export * from './record.service';
import { RecordService } from './record.service';
export * from './record.serviceInterface';
export * from './train.service';
import { TrainService } from './train.service';
export * from './train.serviceInterface';
export * from './ws.service';
import { WsService } from './ws.service';
export * from './ws.serviceInterface';
export const APIS = [AuthService, DetectorService, ProjectService, RecordService, TrainService, WsService];
