/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { RegisterRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Check
     * Checks the current token
     */
    authCheck(extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * Login
     * Performs the login
     * @param username 
     * @param password 
     * @param grantType 
     * @param scope 
     * @param clientId 
     * @param clientSecret 
     */
    authLogin(username: string, password: string, grantType?: string, scope?: string, clientId?: string, clientSecret?: string, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Logout
     * Performs the logout
     */
    authLogout(extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * Password Reset
     * 
     * @param old 
     * @param _new 
     */
    authPasswordReset(old: string, _new: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * Register
     * 
     * @param registerRequest 
     */
    authRegister(registerRequest: RegisterRequest, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * Unregister
     * 
     */
    authUnregister(extraHttpRequestParams?: any): Observable<boolean>;

}
