/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { Project } from '../model/models';
import { ProjectListResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProjectServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create
     * Performs the creation of a project
     * @param name 
     * @param description 
     */
    projectCreate(name: string, description?: string, extraHttpRequestParams?: any): Observable<Project>;

    /**
     * Delete
     * Performs the creation of a project
     * @param id 
     */
    projectDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * List By User
     * 
     * @param skip 
     * @param limit 
     * @param search 
     */
    projectListUser(skip?: number, limit?: number, search?: string, extraHttpRequestParams?: any): Observable<ProjectListResponse>;

    /**
     * Load
     * 
     * @param id 
     */
    projectLoad(id: string, extraHttpRequestParams?: any): Observable<Project>;

    /**
     * Record Count
     * 
     * @param projectId 
     */
    projectRecordCountProjectId(projectId: string, extraHttpRequestParams?: any): Observable<number>;

    /**
     * Update
     * Performs the creation of a project
     * @param id 
     * @param name 
     * @param description 
     */
    projectUpdate(id: string, name: string, description?: string, extraHttpRequestParams?: any): Observable<Project>;

}
