/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { TrainImageObject } from '../model/models';
import { TrainImageObjectListResponse } from '../model/models';
import { TrainImageObjectPayload } from '../model/models';
import { TrainImageObjectUpdatePayload } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TrainerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Image Object Count By Detector
     * 
     * @param detectorId 
     */
    trainerImageObjectCountByDetector(detectorId: string, extraHttpRequestParams?: any): Observable<number>;

    /**
     * Image Object Create
     * 
     * @param trainImageObjectPayload 
     */
    trainerImageObjectCreate(trainImageObjectPayload: TrainImageObjectPayload, extraHttpRequestParams?: any): Observable<TrainImageObject>;

    /**
     * Image Object List
     * 
     * @param detectorId 
     * @param recordId 
     * @param frame 
     */
    trainerImageObjectList(detectorId: string, recordId: string, frame?: number, extraHttpRequestParams?: any): Observable<TrainImageObjectListResponse>;

    /**
     * Image Object Remove
     * 
     * @param objectId 
     */
    trainerImageObjectRemove(objectId: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * Image Object To Detector
     * 
     * @param detectorId 
     */
    trainerImageObjectToDetector(detectorId: string, extraHttpRequestParams?: any): Observable<number>;

    /**
     * Image Object Update
     * 
     * @param trainImageObjectUpdatePayload 
     */
    trainerImageObjectUpdate(trainImageObjectUpdatePayload: TrainImageObjectUpdatePayload, extraHttpRequestParams?: any): Observable<boolean>;

}
