/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { Project } from '../model/models';
import { ProjectListResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WorkspaceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Project
     * Performs the creation of a project
     * @param name 
     * @param description 
     */
    workspaceProjectCreate(name: string, description?: string, extraHttpRequestParams?: any): Observable<Project>;

    /**
     * Delete Project
     * Performs the removal of a project
     * @param projectId 
     */
    workspaceProjectDelete(projectId: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * List Project
     * 
     * @param skip 
     * @param limit 
     * @param search 
     */
    workspaceProjectList(skip?: number, limit?: number, search?: string, extraHttpRequestParams?: any): Observable<ProjectListResponse>;

    /**
     * Load Project
     * 
     * @param projectId 
     */
    workspaceProjectLoad(projectId: string, extraHttpRequestParams?: any): Observable<Project>;

    /**
     * Update Project
     * Performs the update of a project
     * @param projectId 
     * @param name 
     * @param description 
     */
    workspaceProjectUpdate(projectId: string, name: string, description?: string, extraHttpRequestParams?: any): Observable<boolean>;

}
