/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppStartedEvent { 
    _id?: string | null;
    type?: AppStartedEventTypeEnum;
    record: string;
    frame: number;
    synthetic?: boolean;
    timestamp?: string;
    position?: Array<any> | null;
    name: string;
}
export enum AppStartedEventTypeEnum {
    AppStarted = 'app.started'
};



