/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DetectorImageLabel } from './detector-image-label';


export interface DetectorImageLabelListResponse { 
    labels: Array<DetectorImageLabel>;
    total: number;
}

