/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DetectorLabel } from './detector-label';


export interface DetectorClassListResponse { 
    classes: Array<DetectorLabel>;
    total: number;
}

