/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DetectContourNode } from './detect-contour-node';
import { DetectContour } from './detect-contour';


export interface DetectorContoursResponse { 
    contours: Array<DetectContour>;
    nodes: Array<DetectContourNode>;
}

