/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DetectObject { 
    x: number;
    y: number;
    w: number;
    h: number;
    confidence: number;
    code: number;
    name: string;
    row: number;
    col: number;
}

