/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DetectorTrainingSession { 
    type?: DetectorTrainingSessionTypeEnum;
    detector: string;
    total?: number;
    progress?: number;
    message?: string | null;
    error?: string | null;
}
export enum DetectorTrainingSessionTypeEnum {
    DetectorTrainingSession = 'detector.training.session'
};



