/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Detector { 
    _id?: string | null;
    project: string;
    name: string;
    running?: boolean;
    failed?: string | null;
    description?: string | null;
    created?: string;
    updated?: string;
    groups?: Array<string>;
    users?: Array<string>;
    best?: string | null;
    last?: string | null;
}

