/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DetectorImageLabel { 
    _id?: string | null;
    image: string;
    created?: string;
    updated?: string;
    label: string;
    xstart: number;
    xend: number;
    ystart: number;
    yend: number;
}

