/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Detector } from './detector';


export interface DetectorListResponse { 
    detectors: Array<Detector>;
    total: number;
}

