/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KeyReleaseEvent { 
    _id?: string | null;
    type?: KeyReleaseEventTypeEnum;
    record: string;
    frame: number;
    synthetic?: boolean;
    timestamp?: string;
    position?: Array<any> | null;
    key: string;
}
export enum KeyReleaseEventTypeEnum {
    KeyRelease = 'key.release'
};



