/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MousePressRightEvent { 
    _id?: string | null;
    type?: MousePressRightEventTypeEnum;
    record: string;
    frame: number;
    timestamp?: string;
    position?: Array<any> | null;
}
export enum MousePressRightEventTypeEnum {
    MousePressRight = 'mouse.press.right'
};



