/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MouseButton } from './mouse-button';


export interface MouseReleaseEvent { 
    _id?: string | null;
    type?: MouseReleaseEventTypeEnum;
    record: string;
    frame: number;
    synthetic?: boolean;
    timestamp?: string;
    button?: MouseButton;
    position?: Array<any> | null;
}
export enum MouseReleaseEventTypeEnum {
    MouseRelease = 'mouse.release'
};



