/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MouseReleaseMiddleEvent { 
    _id?: string | null;
    type?: MouseReleaseMiddleEventTypeEnum;
    record: string;
    frame: number;
    synthetic?: boolean;
    timestamp?: string;
    position?: Array<any> | null;
}
export enum MouseReleaseMiddleEventTypeEnum {
    MouseReleaseMiddle = 'mouse.release.middle'
};



