/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlayerStepSession { 
    type?: PlayerStepSessionTypeEnum;
    created?: string;
    updated?: string;
    duration: number;
    execution: string;
    message: string;
    total: number;
    progress: number;
    line: number;
    column: number;
    status: boolean;
}
export enum PlayerStepSessionTypeEnum {
    PlayerStepSession = 'player.step.session'
};



