/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OS } from './os';


export interface Record { 
    _id?: string | null;
    project: string;
    name: string;
    os: OS;
    description?: string;
    created?: string;
    updated?: string;
    start?: string;
    end?: string;
    groups?: Array<string>;
    users?: Array<string>;
}

