/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MousePressMiddleEvent } from './mouse-press-middle-event';
import { MouseScrollEvent } from './mouse-scroll-event';
import { MouseClickRightEvent } from './mouse-click-right-event';
import { MousePressRightEvent } from './mouse-press-right-event';
import { MouseDoubleClickEvent } from './mouse-double-click-event';
import { MouseReleaseMiddleEvent } from './mouse-release-middle-event';
import { KeyPressEvent } from './key-press-event';
import { MouseReleaseLeftEvent } from './mouse-release-left-event';
import { KeyComboPressEvent } from './key-combo-press-event';
import { MouseClickLeftEvent } from './mouse-click-left-event';
import { KeyReleaseEvent } from './key-release-event';
import { MouseReleaseRightEvent } from './mouse-release-right-event';
import { MousePressLeftEvent } from './mouse-press-left-event';


/**
 * @type RecordEventListRecordid200ResponseInner
 * @export
 */
export type RecordEventListRecordid200ResponseInner = KeyComboPressEvent | KeyPressEvent | KeyReleaseEvent | MouseClickLeftEvent | MouseClickRightEvent | MouseDoubleClickEvent | MousePressLeftEvent | MousePressMiddleEvent | MousePressRightEvent | MouseReleaseLeftEvent | MouseReleaseMiddleEvent | MouseReleaseRightEvent | MouseScrollEvent;

