/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DetectorTrainingSession } from './detector-training-session';
import { PlayerStepSession } from './player-step-session';


export interface ResponseWebsocketModelsWsModelsGet { 
    type?: ResponseWebsocketModelsWsModelsGetTypeEnum;
    detector: string;
    total: number;
    progress: number;
    message: string;
    error?: string;
    created?: string;
    updated?: string;
    duration: number;
    execution: string;
    line: number;
    column: number;
    status: boolean;
}
export enum ResponseWebsocketModelsWsModelsGetTypeEnum {
    DetectorTrainingSession = 'detector.training.session',
    PlayerStepSession = 'player.step.session'
};



