/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MouseReleaseEvent } from './mouse-release-event';
import { MouseScrollEvent } from './mouse-scroll-event';
import { MouseDropEvent } from './mouse-drop-event';
import { KeyPressEvent } from './key-press-event';
import { KeyComboPressEvent } from './key-combo-press-event';
import { MousePressEvent } from './mouse-press-event';
import { MouseButton } from './mouse-button';
import { MouseDoubleClickEvent } from './mouse-double-click-event';
import { KeyReleaseEvent } from './key-release-event';
import { MouseClickEvent } from './mouse-click-event';


/**
 * @type ResponseRecordereventload
 * @export
 */
export type ResponseRecordereventload = KeyComboPressEvent | KeyPressEvent | KeyReleaseEvent | MouseClickEvent | MouseDoubleClickEvent | MouseDropEvent | MousePressEvent | MouseReleaseEvent | MouseScrollEvent;

