/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrainImageObject } from './train-image-object';


export interface TrainImageObjectListResponse { 
    total: number;
    objects: Array<TrainImageObject>;
}

