/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrainSessionStatus } from './train-session-status';


export interface TrainSession { 
    _id?: string | null;
    detector: string;
    user: string;
    status?: TrainSessionStatus;
    results?: string | null;
    created?: string;
    updated?: string;
    errors?: Array<string>;
}



