/**
 * API
 *
 * Contact: dp@x-force.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrainSession } from './train-session';


export interface TrainSessionListResponse { 
    total: number;
    sessions: Array<TrainSession>;
}

