# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/rpc/base.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'common/rpc/base.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommon/rpc/base.proto\"\x16\n\x04Ping\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x16\n\x04Pong\x12\x0e\n\x06status\x18\x02 \x01(\x08\"-\n\nSerialized\x12\x11\n\tsignature\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\xaa\x01\n\x04Step\x12\r\n\x05order\x18\x01 \x01(\x05\x12\x15\n\x08scenario\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65vent\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x0f\n\x07\x62yClass\x18\x04 \x03(\t\x12\x0e\n\x06\x62yText\x18\x05 \x03(\t\x12\x0f\n\x07\x62yOrder\x18\x06 \x03(\x05\x12\x10\n\x08\x64uration\x18\x07 \x01(\x02\x12\r\n\x05retry\x18\x08 \x01(\x05\x42\x0b\n\t_scenarioB\x08\n\x06_eventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.rpc.base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PING']._serialized_start=25
  _globals['_PING']._serialized_end=47
  _globals['_PONG']._serialized_start=49
  _globals['_PONG']._serialized_end=71
  _globals['_SERIALIZED']._serialized_start=73
  _globals['_SERIALIZED']._serialized_end=118
  _globals['_STEP']._serialized_start=121
  _globals['_STEP']._serialized_end=291
# @@protoc_insertion_point(module_scope)
