# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.rpc import base_pb2 as common_dot_rpc_dot_base__pb2
from common.rpc import storage_pb2 as common_dot_rpc_dot_storage__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in common/rpc/storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/Storage/ping',
                request_serializer=common_dot_rpc_dot_base__pb2.Ping.SerializeToString,
                response_deserializer=common_dot_rpc_dot_base__pb2.Pong.FromString,
                _registered_method=True)
        self.storageSave = channel.unary_unary(
                '/Storage/storageSave',
                request_serializer=common_dot_rpc_dot_storage__pb2.StorageSaveRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_storage__pb2.StorageSaveResponse.FromString,
                _registered_method=True)
        self.storageLoad = channel.unary_unary(
                '/Storage/storageLoad',
                request_serializer=common_dot_rpc_dot_storage__pb2.StorageLoadRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_storage__pb2.StorageLoadResponse.FromString,
                _registered_method=True)
        self.storageLoadById = channel.unary_unary(
                '/Storage/storageLoadById',
                request_serializer=common_dot_rpc_dot_storage__pb2.StorageLoadByIdRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_storage__pb2.StorageLoadByIdResponse.FromString,
                _registered_method=True)
        self.storageExists = channel.unary_unary(
                '/Storage/storageExists',
                request_serializer=common_dot_rpc_dot_storage__pb2.StorageExistsRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_storage__pb2.StorageExistsResponse.FromString,
                _registered_method=True)
        self.storageRemove = channel.unary_unary(
                '/Storage/storageRemove',
                request_serializer=common_dot_rpc_dot_storage__pb2.StorageRemoveRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_storage__pb2.StorageRemoveResponse.FromString,
                _registered_method=True)
        self.storageRemoveFolder = channel.unary_unary(
                '/Storage/storageRemoveFolder',
                request_serializer=common_dot_rpc_dot_storage__pb2.StorageRemoveFolderRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_storage__pb2.StorageRemoveFolderResponse.FromString,
                _registered_method=True)


class StorageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ping(self, request, context):
        """Performs synchronous ping of service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def storageSave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def storageLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def storageLoadById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def storageExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def storageRemove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def storageRemoveFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=common_dot_rpc_dot_base__pb2.Ping.FromString,
                    response_serializer=common_dot_rpc_dot_base__pb2.Pong.SerializeToString,
            ),
            'storageSave': grpc.unary_unary_rpc_method_handler(
                    servicer.storageSave,
                    request_deserializer=common_dot_rpc_dot_storage__pb2.StorageSaveRequest.FromString,
                    response_serializer=common_dot_rpc_dot_storage__pb2.StorageSaveResponse.SerializeToString,
            ),
            'storageLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.storageLoad,
                    request_deserializer=common_dot_rpc_dot_storage__pb2.StorageLoadRequest.FromString,
                    response_serializer=common_dot_rpc_dot_storage__pb2.StorageLoadResponse.SerializeToString,
            ),
            'storageLoadById': grpc.unary_unary_rpc_method_handler(
                    servicer.storageLoadById,
                    request_deserializer=common_dot_rpc_dot_storage__pb2.StorageLoadByIdRequest.FromString,
                    response_serializer=common_dot_rpc_dot_storage__pb2.StorageLoadByIdResponse.SerializeToString,
            ),
            'storageExists': grpc.unary_unary_rpc_method_handler(
                    servicer.storageExists,
                    request_deserializer=common_dot_rpc_dot_storage__pb2.StorageExistsRequest.FromString,
                    response_serializer=common_dot_rpc_dot_storage__pb2.StorageExistsResponse.SerializeToString,
            ),
            'storageRemove': grpc.unary_unary_rpc_method_handler(
                    servicer.storageRemove,
                    request_deserializer=common_dot_rpc_dot_storage__pb2.StorageRemoveRequest.FromString,
                    response_serializer=common_dot_rpc_dot_storage__pb2.StorageRemoveResponse.SerializeToString,
            ),
            'storageRemoveFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.storageRemoveFolder,
                    request_deserializer=common_dot_rpc_dot_storage__pb2.StorageRemoveFolderRequest.FromString,
                    response_serializer=common_dot_rpc_dot_storage__pb2.StorageRemoveFolderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Storage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Storage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Storage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Storage/ping',
            common_dot_rpc_dot_base__pb2.Ping.SerializeToString,
            common_dot_rpc_dot_base__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def storageSave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Storage/storageSave',
            common_dot_rpc_dot_storage__pb2.StorageSaveRequest.SerializeToString,
            common_dot_rpc_dot_storage__pb2.StorageSaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def storageLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Storage/storageLoad',
            common_dot_rpc_dot_storage__pb2.StorageLoadRequest.SerializeToString,
            common_dot_rpc_dot_storage__pb2.StorageLoadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def storageLoadById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Storage/storageLoadById',
            common_dot_rpc_dot_storage__pb2.StorageLoadByIdRequest.SerializeToString,
            common_dot_rpc_dot_storage__pb2.StorageLoadByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def storageExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Storage/storageExists',
            common_dot_rpc_dot_storage__pb2.StorageExistsRequest.SerializeToString,
            common_dot_rpc_dot_storage__pb2.StorageExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def storageRemove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Storage/storageRemove',
            common_dot_rpc_dot_storage__pb2.StorageRemoveRequest.SerializeToString,
            common_dot_rpc_dot_storage__pb2.StorageRemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def storageRemoveFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Storage/storageRemoveFolder',
            common_dot_rpc_dot_storage__pb2.StorageRemoveFolderRequest.SerializeToString,
            common_dot_rpc_dot_storage__pb2.StorageRemoveFolderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
