# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.rpc import base_pb2 as common_dot_rpc_dot_base__pb2
from common.rpc import trainer_pb2 as common_dot_rpc_dot_trainer__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in common/rpc/trainer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/Trainer/ping',
                request_serializer=common_dot_rpc_dot_base__pb2.Ping.SerializeToString,
                response_deserializer=common_dot_rpc_dot_base__pb2.Pong.FromString,
                _registered_method=True)
        self.recordHasLesson = channel.unary_unary(
                '/Trainer/recordHasLesson',
                request_serializer=common_dot_rpc_dot_trainer__pb2.RecordHasLessonRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_trainer__pb2.RecordHasLessonResponse.FromString,
                _registered_method=True)
        self.recordCreateLesson = channel.unary_unary(
                '/Trainer/recordCreateLesson',
                request_serializer=common_dot_rpc_dot_trainer__pb2.RecordCreateLessonRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_trainer__pb2.RecordCreateLessonResponse.FromString,
                _registered_method=True)
        self.lessonSetDetector = channel.unary_unary(
                '/Trainer/lessonSetDetector',
                request_serializer=common_dot_rpc_dot_trainer__pb2.LessonSetDetectorRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_trainer__pb2.LessonSetDetectorResponse.FromString,
                _registered_method=True)
        self.trainImageObject = channel.unary_unary(
                '/Trainer/trainImageObject',
                request_serializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectResponse.FromString,
                _registered_method=True)
        self.trainImageObjectList = channel.unary_unary(
                '/Trainer/trainImageObjectList',
                request_serializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectListRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectListResponse.FromString,
                _registered_method=True)
        self.trainImageObjectRemove = channel.unary_unary(
                '/Trainer/trainImageObjectRemove',
                request_serializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectRemoveRequest.SerializeToString,
                response_deserializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectRemoveResponse.FromString,
                _registered_method=True)


class TrainerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ping(self, request, context):
        """Performs synchronous ping of service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def recordHasLesson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def recordCreateLesson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def lessonSetDetector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def trainImageObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def trainImageObjectList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def trainImageObjectRemove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=common_dot_rpc_dot_base__pb2.Ping.FromString,
                    response_serializer=common_dot_rpc_dot_base__pb2.Pong.SerializeToString,
            ),
            'recordHasLesson': grpc.unary_unary_rpc_method_handler(
                    servicer.recordHasLesson,
                    request_deserializer=common_dot_rpc_dot_trainer__pb2.RecordHasLessonRequest.FromString,
                    response_serializer=common_dot_rpc_dot_trainer__pb2.RecordHasLessonResponse.SerializeToString,
            ),
            'recordCreateLesson': grpc.unary_unary_rpc_method_handler(
                    servicer.recordCreateLesson,
                    request_deserializer=common_dot_rpc_dot_trainer__pb2.RecordCreateLessonRequest.FromString,
                    response_serializer=common_dot_rpc_dot_trainer__pb2.RecordCreateLessonResponse.SerializeToString,
            ),
            'lessonSetDetector': grpc.unary_unary_rpc_method_handler(
                    servicer.lessonSetDetector,
                    request_deserializer=common_dot_rpc_dot_trainer__pb2.LessonSetDetectorRequest.FromString,
                    response_serializer=common_dot_rpc_dot_trainer__pb2.LessonSetDetectorResponse.SerializeToString,
            ),
            'trainImageObject': grpc.unary_unary_rpc_method_handler(
                    servicer.trainImageObject,
                    request_deserializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectRequest.FromString,
                    response_serializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectResponse.SerializeToString,
            ),
            'trainImageObjectList': grpc.unary_unary_rpc_method_handler(
                    servicer.trainImageObjectList,
                    request_deserializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectListRequest.FromString,
                    response_serializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectListResponse.SerializeToString,
            ),
            'trainImageObjectRemove': grpc.unary_unary_rpc_method_handler(
                    servicer.trainImageObjectRemove,
                    request_deserializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectRemoveRequest.FromString,
                    response_serializer=common_dot_rpc_dot_trainer__pb2.TrainImageObjectRemoveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Trainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Trainer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Trainer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Trainer/ping',
            common_dot_rpc_dot_base__pb2.Ping.SerializeToString,
            common_dot_rpc_dot_base__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def recordHasLesson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Trainer/recordHasLesson',
            common_dot_rpc_dot_trainer__pb2.RecordHasLessonRequest.SerializeToString,
            common_dot_rpc_dot_trainer__pb2.RecordHasLessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def recordCreateLesson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Trainer/recordCreateLesson',
            common_dot_rpc_dot_trainer__pb2.RecordCreateLessonRequest.SerializeToString,
            common_dot_rpc_dot_trainer__pb2.RecordCreateLessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def lessonSetDetector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Trainer/lessonSetDetector',
            common_dot_rpc_dot_trainer__pb2.LessonSetDetectorRequest.SerializeToString,
            common_dot_rpc_dot_trainer__pb2.LessonSetDetectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def trainImageObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Trainer/trainImageObject',
            common_dot_rpc_dot_trainer__pb2.TrainImageObjectRequest.SerializeToString,
            common_dot_rpc_dot_trainer__pb2.TrainImageObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def trainImageObjectList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Trainer/trainImageObjectList',
            common_dot_rpc_dot_trainer__pb2.TrainImageObjectListRequest.SerializeToString,
            common_dot_rpc_dot_trainer__pb2.TrainImageObjectListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def trainImageObjectRemove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Trainer/trainImageObjectRemove',
            common_dot_rpc_dot_trainer__pb2.TrainImageObjectRemoveRequest.SerializeToString,
            common_dot_rpc_dot_trainer__pb2.TrainImageObjectRemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
